### PR TITLE
Update laravel to v11 and other composer dependencies

### PR DESCRIPTION
**Pull request by Arthur-Sk**

### CODE REVIEW

**Comment by Arthur-Sk** [comment]
Hey @belamov, can you take a look at this PR, please? We cannot update Laravel to the latest versions without these changes

**Comment by belamov** [comment]
hey @Arthur-Sk thanks for pr!

could you please update testing matrix aswell, so we can make sure this packege is working on laravel 11?

https://github.com/belamov/postgres-range/blob/master/.github/workflows/main.yml#L37

**Comment by belamov** [comment]
some tests are failng

please exclude them from matrix if this is dependency problem, for example: https://github.com/belamov/postgres-range/actions/runs/8387175011/job/22969055071?pr=26

**Comment by Arthur-Sk** [comment]
Sure, I'm in progress already

**Comment by Arthur-Sk** [comment]
Good to go

**Comment by belamov** [comment]
thanks a lot!

**Comment by belamov** [comment]
@Arthur-Sk released new minor version, so you shold be able to update laravel iin your project

**Pull request merged**
